# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuristManagment', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_availability',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
