# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuristManagment', '0003_room_room_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_member',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_availability',
            field=models.IntegerField(),
        ),
    ]
