# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuristManagment', '0004_auto_20171212_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('night', models.IntegerField()),
                ('adult', models.IntegerField()),
                ('children', models.IntegerField(null=True)),
            ],
        ),
    ]
