# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuristManagment', '0005_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='adult',
            field=models.IntegerField(null=True),
        ),
    ]
