# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuristManagment', '0006_auto_20171212_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200, null=True)),
                ('town', models.CharField(max_length=30, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30)),
                ('passport_number', models.IntegerField()),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
