# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuristManagment', '0007_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.IntegerField(null=True),
        ),
    ]
