# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuristManagment', '0008_booking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.IntegerField(auto_created=True),
        ),
    ]
