# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuristManagment', '0009_auto_20171213_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
