# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TuristManagment', '0010_reservation_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='booking_id',
        ),
    ]
