# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TuristManagment', '0014_employees_empemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='deptID',
        ),
    ]
