# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TuristManagment', '0017_demodatabase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demodatabase',
        ),
    ]
