# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuristManagment', '0018_delete_demodatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
